# Generated by Django 4.0.1 on 2022-01-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_type'),
        ('issue', '0007_alter_issue_creator_alter_issue_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_issue', to='project.project'),
        ),
    ]
