# Generated by Django 4.0.1 on 2022-01-28 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CREATOR', 'Creator'), ('CONTRIBUTOR', 'Contributor')], max_length=30, verbose_name='rôle')),
                ('contributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_id', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_id', to='project.project')),
            ],
        ),
    ]
