# Generated by Django 4.0.1 on 2022-01-28 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_alter_project_type'),
        ('contributor', '0002_alter_contributor_contributor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='contributor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to='project.project'),
        ),
    ]
