# Generated by Django 4.0.1 on 2022-01-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('back-end', 'Back End'), ('front-end', 'Front End'), ('IOS', 'Ios'), ('Android', 'Android')], max_length=10),
        ),
    ]
