# Generated by Django 4.0.1 on 2022-01-19 10:24

from django.db import migrations


def create_groups(apps, schema_migration):
    Contributor = apps.get_model('api', 'Contributor')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_contributor = Permission.objects.get(codename='add_contributor')
    change_contributor = Permission.objects.get(codename='add_contributor')
    delete_contributor = Permission.objects.get(codename='add_contributor')
    view_contributor = Permission.objects.get(codename='add_contributor')
    
    creator_permissions = [
        add_contributor,
        change_contributor,
        delete_contributor,
        view_contributor,
    ]
    
    creators = Group(name='creators')
    creators.save()
    
    creators.permissions.set(creator_permissions)

    contributors = Group(name='contributor')
    contributors.save()
    contributors.permissions.add(view_contributor)
    
    for user in Contributor.objects.all():
        if user.role == 'CREATOR':
            creators.user_set.add(user)
        if user.role == 'CONTRIBUTOR':
            contributors.user_set.add(user)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
