# Generated by Django 4.0.1 on 2022-01-23 13:39

from django.db import migrations

def porject(apps, schema_migration):
    User = apps.get_model('api', 'Contributor')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_project = Permission.objects.get(codename='add_project')
    change_project = Permission.objects.get(codename='change_project')
    delete_project = Permission.objects.get(codename='delete_project')
    view_project = Permission.objects.get(codename='view_project')
    
    creator_permissions = [
        add_project,
        change_project,
        delete_project,
        view_project,
    ]
    
    creators = Group(name='creators')
    creators.save()
    
    creators.permissions.set(creator_permissions)

    contributors = Group(name='contributors')
    contributors.save()
    contributors.permissions.add(view_project)
    
    for user in User.objects.all():
        if user.role == 'CREATOR':
            creators.user_set.add(user)
        if user.role == 'SUBSCRIBER':
            contributors.user_set.add(user)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_issue_com'),
    ]

    operations = [
        migrations.RunPython(porject)
    ]
