# Generated by Django 4.0.1 on 2022-01-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220119_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='desc',
            new_name='description',
        ),
    ]
