# Generated by Django 4.0.1 on 2022-01-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_desc_issue_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Com',
        ),
    ]
